### ISSUE TITLE
[BUG] when pushing template with no changes, generic error is returned

### ISSUE THREAD

**Issue by craigcraigcraig** [blueseph/cirrus#1]
**Describe the bug**
when pushing template with no changes, error returned should be more descriptive (or at least the error returned from the changeset operation)

**To Reproduce**
cirrus up
wait for success
cirrus up (without making any changes)
Error returned:  ResourceNotReady: failed waiting for successful resource state

**Expected behavior**
Error returned:  The submitted information didn't contain changes. Submit different information to create a change set

**Comment by blueseph** [comment]
fixed by cfbaf51
