### ISSUE TITLE
[BUG] declining a changeset results in unexepected "[ERROR] User declined delete" and changeset is retained

### ISSUE THREAD

**Issue by craigcraigcraig** [blueseph/cirrus#2]
**Describe the bug**
when i decline a changeset, I get the error:  User declined delete.  I'd expect a success message.  Also, the changeset is retained.  Is there value in retaining a declined changeset (as a beginner)?

**To Reproduce**
cirrus up
decline the changeset
[ERROR] User declined delete
*also...  the program exits without an error code, which contradicts the label [ERROR]

**Expected behavior**
[INFO] "Stack operation declined. No changes made to stack." (or something along those lines).  I made up the INFO tag.

**Comment by blueseph** [comment]
fixed by 551698e
